INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Albania Lek', 'ALL');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Afghanistan Afghani', 'AFN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Argentina Peso', 'ARS');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Aruba Guilder', 'AWG');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Australia Dollar', 'AUD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Azerbaijan Manat', 'AZN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Bahamas Dollar', 'BSD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Barbados Dollar', 'BBD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Belarus Ruble', 'BYN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Belize Dollar', 'BZD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Bermuda Dollar', 'BMD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Bolivia Bolíviano', 'BOB');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Bosnia and Herzegovina Convertible Mark', 'BAM');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Botswana Pula', 'BWP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Bulgaria Lev', 'BGN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Brazil Real', 'BRL');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Brunei Darussalam Dollar', 'BND');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Cambodia Riel', 'KHR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Canada Dollar', 'CAD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Cayman Islands Dollar', 'KYD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Chile Peso', 'CLP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('China Yuan Renminbi', 'CNY');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Colombia Peso', 'COP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Costa Rica Colon', 'CRC');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Croatia Kuna', 'HRK');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Cuba Peso', 'CUP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Czech Republic Koruna', 'CZK');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Denmark Krone', 'DKK');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Dominican Republic Peso', 'DOP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('East Caribbean Dollar', 'XCD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Egypt Pound', 'EGP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('El Salvador Colon', 'SVC');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Euro Member Countries', 'EUR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Falkland Islands (Malvinas) Pound', 'FKP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Fiji Dollar', 'FJD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Ghana Cedi', 'GHS');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Gibraltar Pound', 'GIP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Guatemala Quetzal', 'GTQ');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Guernsey Pound', 'GGP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Guyana Dollar', 'GYD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Honduras Lempira', 'HNL');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Hong Kong Dollar', 'HKD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Hungary Forint', 'HUF');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Iceland Krona', 'ISK');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('India Rupee', 'INR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Indonesia Rupiah', 'IDR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Iran Rial', 'IRR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Isle of Man Pound', 'IMP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Israel Shekel', 'ILS');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Jamaica Dollar', 'JMD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Japan Yen', 'JPY');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Jersey Pound', 'JEP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Kazakhstan Tenge', 'KZT');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Korea (North) Won', 'KPW');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Korea (South) Won', 'KRW');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Kyrgyzstan Som', 'KGS');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Laos Kip', 'LAK');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Lebanon Pound', 'LBP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Liberia Dollar', 'LRD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Macedonia Denar', 'MKD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Malaysia Ringgit', 'MYR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Mauritius Rupee', 'MUR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Mexico Peso', 'MXN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Mongolia Tughrik', 'MNT');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Moroccan-dirham', 'MNTd');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Mozambique Metical', 'MZN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Namibia Dollar', 'NAD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Nepal Rupee', 'NPR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Netherlands Antilles Guilder', 'ANG');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('New Zealand Dollar', 'NZD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Nicaragua Cordoba', 'NIO');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Nigeria Naira', 'NGN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Norway Krone', 'NOK');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Oman Rial', 'OMR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Pakistan Rupee', 'PKR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Panama Balboa', 'PAB');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Paraguay Guarani', 'PYG');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Peru Sol', 'PEN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Philippines Peso', 'PHP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Poland Zloty', 'PLN');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Qatar Riyal', 'QAR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Romania Leu', 'RON');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Russia Ruble', 'RUB');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Saint Helena Pound', 'SHP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Saudi Arabia Riyal', 'SAR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Serbia Dinar', 'RSD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Seychelles Rupee', 'SCR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Singapore Dollar', 'SGD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Solomon Islands Dollar', 'SBD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Somalia Shilling', 'SOS');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('South Africa Rand', 'ZAR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Sri Lanka Rupee', 'LKR');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Sweden Krona', 'SEK');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Switzerland Franc', 'CHF');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Suriname Dollar', 'SRD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Syria Pound', 'SYP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Taiwan New Dollar', 'TWD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Thailand Baht', 'THB');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Trinidad and Tobago Dollar', 'TTD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Turkey Lira', 'TRY');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Tuvalu Dollar', 'TVD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Ukraine Hryvnia', 'UAH');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('UAE-Dirham', 'AED');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('United Kingdom Pound', 'GBP');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('United States Dollar', 'USD');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Uruguay Peso', 'UYU');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Uzbekistan Som', 'UZS');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Venezuela Bolívar', 'VEF');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Viet Nam Dong', 'VND');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Yemen Rial', 'YER');
INSERT OR IGNORE INTO Currencies (currency_name, symbol) VALUES ('Zimbabwe Dollar', 'ZWD');